//////// Menu file loading
//var post = document.querySelector("link[rel = 'import']").import;
//var con = post.querySelector("#navi");
//var node = document.querySelector("#page-wrapper");
//document.querySelector("#wrapper").insertBefore(con, node);
if (document.querySelector("link[rel = 'import']").import) {
    // 支持
    var post = document.querySelector("link[rel = 'import']").import;
    var con = post.querySelector("#navi");
    var node = document.querySelector("#page-wrapper");
    document.querySelector("#wrapper").insertBefore(con, node);
} else {
    // 不支持

    document.writeln("<div id=\'navi\'>");
    document.writeln("    <!-- navigation -->");
    document.writeln("    <nav class=\'navbar navbar-default navbar-static-top\' role=\'navigation\' style=\'margin-bottom: 0\'>");
    document.writeln("        <div class=\'navbar-header\'>");
    document.writeln("            <button type=\'button\' class=\'navbar-toggle\' data-toggle=\'collapse\' data-target=\'.navbar-collapse\'>");
    document.writeln("                <span class=\'sr-only\'>toggle navigation</span>");
    document.writeln("                <span class=\'icon-bar\'></span>");
    document.writeln("                <span class=\'icon-bar\'></span>");
    document.writeln("                <span class=\'icon-bar\'></span>");
    document.writeln("            </button>");
    document.writeln("            <a class=\'navbar-brand\' href=\'index.html\'>支付网关管理系统后台beta</a>");
    document.writeln("        </div>");
    document.writeln("        <!-- /.navbar-header -->");
    document.writeln("");
    document.writeln("        <ul class=\'nav navbar-top-links navbar-right\'>");
    document.writeln("            <li class=\'dropdown\'>");
    document.writeln("                <a class=\'dropdown-toggle\' data-toggle=\'dropdown\' href=\'#\'>");
    document.writeln("                    <i class=\'fa fa-user fa-fw\'></i> <i class=\'fa fa-caret-down\'></i>");
    document.writeln("                </a>");
    document.writeln("                <ul class=\'dropdown-menu dropdown-user\'>");
    document.writeln("                    <li>");
    document.writeln("                        <a href=\'staff.html\'><i class=\'fa fa-user fa-fw\'></i> 登录账号</a>");
    document.writeln("                    </li>");
    document.writeln("                    <li>");
    document.writeln("                        <a href=\'settings.html\'><i class=\'fa fa-gear fa-fw\'></i> 系统设置</a>");
    document.writeln("                    </li>");
    document.writeln("                    <li class=\'divider\'></li>");
    document.writeln("                    <li id=\'logout\'>");
    document.writeln("                        <a id=\'logout\' href=\'login.html\'><i class=\'fa fa-sign-out fa-fw\'></i> 注销登录</a>");
    document.writeln("                    </li>");
    document.writeln("                </ul>");
    document.writeln("                <!-- /.dropdown-user -->");
    document.writeln("            </li>");
    document.writeln("            <!-- /.dropdown -->");
    document.writeln("        </ul>");
    document.writeln("        <!-- /.navbar-top-links -->");
    document.writeln("");
    document.writeln("        <div class=\'navbar-default sidebar\' role=\'navigation\'>");
    document.writeln("            <div class=\'sidebar-nav navbar-collapse\'>");
    document.writeln("                <ul class=\'nav\' id=\'side-menu\'>");
    document.writeln("                    <li class=\'sidebar-search\'>");
    document.writeln("                        <div class=\'input-group custom-search-form\'>");
    document.writeln("                            <input type=\'text\' class=\'form-control\' placeholder=\'查找...\'>");
    document.writeln("                            <span class=\'input-group-btn\'>");
    document.writeln("                                <button class=\'btn btn-default\' type=\'button\'>");
    document.writeln("                                    <i class=\'fa fa-search\'></i>");
    document.writeln("                                </button>");
    document.writeln("                            </span>");
    document.writeln("                        </div>");
    document.writeln("                        <!-- /input-group -->");
    document.writeln("                    </li>");
    document.writeln("                    <li>");
    document.writeln("                        <a href=\'index.html\'><i class=\'fa fa-dashboard fa-fw\'></i> 仪表盘</a>");
    document.writeln("                    </li>");
    document.writeln("                    <li>");
    document.writeln("                        <a href=\'#\'><i class=\'fa fa-users fa-fw\'></i> 商户管理<span class=\'fa arrow\'></span></a>");
    document.writeln("                        <ul class=\'nav nav-second-level\'>");
    document.writeln("                            <li>");
    document.writeln("                                <a href=\'merchant.html\'>商户信息</a>");
    document.writeln("                            </li>");
    document.writeln("                            <li>");
    document.writeln("                                <a href=\'store.html\'>门店信息</a>");
    document.writeln("                            </li>");
    document.writeln("                            <li>");
    document.writeln("                                <a href=\'staff.html\'>用户信息</a>");
    document.writeln("                            </li>");
    document.writeln("                        </ul>");
    document.writeln("                    </li>");
    document.writeln("                    <li>");
    document.writeln("                        <a href=\'#\'><i class=\'fa fa-tags fa-fw\'></i> 商品管理<span class=\'fa arrow\'></span></a>");
    document.writeln("                        <ul class=\'nav nav-second-level\'>");
    document.writeln("                            <li>");
    document.writeln("                                <a href=\'product.html\'>产品管理</a>");
    document.writeln("                            </li>");
    document.writeln("                            <li>");
    document.writeln("                                <a href=\'vendor.html\'>供应商管理</a>");
    document.writeln("                            </li>");
    document.writeln("                            <li>");
    document.writeln("                                <a href=\'hierarchy.html\'>产品层级管理</a>");
    document.writeln("                            </li>");
    document.writeln("                        </ul>");
    document.writeln("                    </li>");
    document.writeln("                    <li>");
    document.writeln("                        <a href=\'#\'><i class=\'fa fa-money fa-fw\'></i> 支付管理<span class=\'fa arrow\'></span></a>");
    document.writeln("                        <ul class=\'nav nav-second-level\'>");
    document.writeln("                            <li>");
    document.writeln("                                <a href=\'account.html\'>支付账号管理</a>");
    document.writeln("                            </li>");
    document.writeln("                            <li>");
    document.writeln("                                <a href=\'storeaccount.html\'>支付方式管理</a>");
    document.writeln("                            </li>");
    document.writeln("                        </ul>");
    document.writeln("                        <!-- /.nav-second-level -->");
    document.writeln("                    </li>");
    document.writeln("                    <li>");
    document.writeln("                        <a href=\'#\'><i class=\'fa fa-bank fa-fw\'></i> 订单管理<span class=\'fa arrow\'></span></a>");
    document.writeln("                        <ul class=\'nav nav-second-level\'>");
    document.writeln("                            <li>");
    document.writeln("                                <a href=\'orders.html\'>订单状态管理</a>");
    document.writeln("                            </li>");
    document.writeln("                        </ul>");
    document.writeln("                    </li>");
    document.writeln("                    <li>");
    document.writeln("                        <a href=\'#\'><i class=\'fa fa-check-circle fa-fw\'></i> 对账管理<span class=\'fa arrow\'></span></a>");
    document.writeln("                        <ul class=\'nav nav-second-level\'>");
    document.writeln("                            <li>");
    document.writeln("                                <a href=\'checking.html\'>对账记录管理</a>");
    document.writeln("                            </li>");
    document.writeln("                        </ul>");
    document.writeln("                    </li>");
    document.writeln("                </ul>");
    document.writeln("            </div>");
    document.writeln("            <!-- /.sidebar-collapse -->");
    document.writeln("        </div>");
    document.writeln("        <!-- /.navbar-static-side -->");
    document.writeln("    </nav>");
    document.writeln("    <!-- /navigation -->");
    document.writeln("");
    document.writeln("</div>");

}



//var frame = document.getElementsByTagName("iframe")[0];
//var h = frame.contentWindow.document.getElementById("navi");
//var x = document.importNode(h,true);
//document.getElementById("wrapper").appendChild(h);
//document.getElementById("ifmenu").style.display = "none";